name: Build and Deploy

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      kubero_app_path:
        required: true
        type: string
      kubero_domain_worker_path:
        required: true
        type: string
      kubero_email_worker_path:
        required: true
        type: string
      kubero_invoice_worker_path:
        required: true
        type: string

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v4

      - id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "image_tag=prod" >> "$GITHUB_OUTPUT"
          else
            echo "image_tag=develop" >> "$GITHUB_OUTPUT"
          fi

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ inputs.image_name }}:${{ steps.vars.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

    steps:
      - name: Authenticate with Kubero
        id: kubero-auth
        run: |
          TOKEN=$(curl --silent --location \
            '${{ secrets.KUBERO_ENDPOINT }}/api/auth/login' \
            --header 'Content-Type: application/json' \
            --data '{
              "username": "${{ secrets.KUBERO_USERNAME }}",
              "password": "${{ secrets.KUBERO_PASSWORD }}"
            }' | jq -r '.access_token')

          if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
            echo "Failed to get Kubero JWT token"
            exit 1
          fi

          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - name: Restart Kubero App
        run: |
          restart() {
            local path="$1"
            
            curl --fail --request GET \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer ${{ steps.kubero-auth.outputs.token }}" \
            "${{ secrets.KUBERO_ENDPOINT }}${path}"
          }

          restart "${{ inputs.kubero_app_path }}"

          restart "${{ inputs.kubero_domain_worker_path }}"
          
          restart "${{ inputs.kubero_email_worker_path }}"
          
          restart "${{ inputs.kubero_invoice_worker_path }}"
